language: php
php:
  - 5.3
  - 5.4
before_script:
  - git clone git://github.com/n1k0/casperjs.git
  - cd casperjs
  - git checkout tags/1.0.0-RC1
  - sudo ln -sf `pwd`/bin/casperjs /usr/local/bin/casperjs
  - cd ~/builds/proximitybbdo/proximinade
  - export PHANTOMJS_EXECUTABLE='phantomjs --local-to-remote-url-access=yes --ignore-ssl-errors=yes'
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: make test

notifications:
  email:
    recipients:
      - jeroen.bourgois@proximity.bbdo.be
      - info@jeroenbourgois.be
      - pieter.michels@proximity.bbdo.be
