language: php
php:
  - 5.3
  - 5.4
before_script:
  - pwd
  - sudo apt-get install nginx
  - sudo apt-get install php5-fpm
  - sudo cp .travis.nginx.conf /etc/nginx/nginx.conf
  - sudo /etc/init.d/nginx restart
  - sleep 3
  - git clone git://github.com/n1k0/casperjs.git
  - cd casperjs
  - git checkout tags/1.0.0-RC1
  - sudo ln -sf `pwd`/bin/casperjs /usr/local/bin/casperjs
  - sleep 3
  - chmod -R 777 /home/vagrant/builds/proximitybbdo/proximinade
  - cd /home/vagrant/builds/proximitybbdo/proximinade
  - "export PHANTOMJS_EXECUTABLE='phantomjs --local-to-remote-url-access=yes --ignore-ssl-errors=yes'"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - curl -I http://localhost:3000
script: make test

notifications:
  email:
    recipients:
      - jeroen.bourgois@proximity.bbdo.be
      - info@jeroenbourgois.be
      # - pieter.michels@proximity.bbdo.be
